# Generated by Django 5.1.5 on 2025-02-03 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
