# Generated by Django 5.1.5 on 2025-02-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_delete_contact'),
        ('tags', '0003_rename_create_at_tag_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, to='tags.tag'),
        ),
    ]
