# Generated by Django 5.1.5 on 2025-02-03 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_remove_post_tag_post_tag'),
        ('tags', '0003_rename_create_at_tag_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='tags.tag'),
            preserve_default=False,
        ),
    ]
