# Generated by Django 5.1.5 on 2025-02-02 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='created_at',
            new_name='create_at',
        ),
    ]
