# Generated by Django 5.1.5 on 2025-02-02 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_rename_create_at_category_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
