# Generated by Django 5.1.5 on 2025-02-02 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_rename_created_at_tag_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
